# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

citbincvr <- function(L, G, T, C, CG, maxit, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbincvr', PACKAGE = 'CITpkg', L, G, T, C, CG, maxit, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, pval3nc, rseed))
}

citbincvr_linear <- function(L, G, T, C, CG, maxit, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbincvr_linear', PACKAGE = 'CITpkg', L, G, T, C, CG, maxit, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, pval3nc, rseed))
}

citbinmcvr <- function(L, G, T, C, maxit, nrow, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbinmcvr', PACKAGE = 'CITpkg', L, G, T, C, maxit, nrow, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, rseed))
}

citbinmcvr_linear <- function(L, G, T, C, maxit, nrow, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbinmcvr_linear', PACKAGE = 'CITpkg', L, G, T, C, maxit, nrow, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, rseed))
}

citbinmpcvr <- function(L, G, T, C, maxit, permit, permnum, nobs, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinmpcvr', PACKAGE = 'CITpkg', L, G, T, C, maxit, permit, permnum, nobs, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, perm_index, rseed))
}

citbinmpcvr_linear <- function(L, G, T, C, maxit, permit, permnum, nobs, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinmpcvr_linear', PACKAGE = 'CITpkg', L, G, T, C, maxit, permit, permnum, nobs, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, perm_index, rseed))
}

citbinpcvr <- function(L, G, T, C, CG, maxit, permit, boots, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinpcvr', PACKAGE = 'CITpkg', L, G, T, C, CG, maxit, permit, boots, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed))
}

citbinpcvr_linear <- function(L, G, T, C, CG, maxit, permit, boots, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinpcvr_linear', PACKAGE = 'CITpkg', L, G, T, C, CG, maxit, permit, boots, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed))
}

citconlog2cvr <- function(L, G, T, C, CG, nrow, ncol, ncolc, ncolct, pval, pval1, pval2, pval3, pval4, maxit, rseed) {
    invisible(.Call('_CITpkg_citconlog2cvr', PACKAGE = 'CITpkg', L, G, T, C, CG, nrow, ncol, ncolc, ncolct, pval, pval1, pval2, pval3, pval4, maxit, rseed))
}

citconlog2cvr_linear <- function(L, G, T, C, CG, nrow, ncol, ncolc, ncolct, pval, pval1, pval2, pval3, pval4, maxit, rseed) {
    invisible(.Call('_CITpkg_citconlog2cvr_linear', PACKAGE = 'CITpkg', L, G, T, C, CG, nrow, ncol, ncolc, ncolct, pval, pval1, pval2, pval3, pval4, maxit, rseed))
}

citconlog3pcvr <- function(L, G, T, C, CG, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed) {
    invisible(.Call('_CITpkg_citconlog3pcvr', PACKAGE = 'CITpkg', L, G, T, C, CG, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed))
}

citconlog3pcvr_linear <- function(L, G, T, C, CG, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed) {
    invisible(.Call('_CITpkg_citconlog3pcvr_linear', PACKAGE = 'CITpkg', L, G, T, C, CG, nrow, ncol, ncolc, ncolct, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed))
}

