# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

citbin <- function(L, G, T, maxit, nrow, ncol, pval1, pval2, pval3, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbin', PACKAGE = 'CITpkg', L, G, T, maxit, nrow, ncol, pval1, pval2, pval3, pval4, pval3nc, rseed))
}

citbin_linear <- function(L, G, T, maxit, nrow, ncol, pval1, pval2, pval3, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbin_linear', PACKAGE = 'CITpkg', L, G, T, maxit, nrow, ncol, pval1, pval2, pval3, pval4, pval3nc, rseed))
}

citbincvr <- function(L, G, T, C, maxit, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbincvr', PACKAGE = 'CITpkg', L, G, T, C, maxit, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, pval3nc, rseed))
}

citbincvr_linear <- function(L, G, T, C, maxit, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbincvr_linear', PACKAGE = 'CITpkg', L, G, T, C, maxit, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, pval3nc, rseed))
}

citbinm <- function(L, G, T, maxit, nrow, dfz, dfx, pval1, pval2, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbinm', PACKAGE = 'CITpkg', L, G, T, maxit, nrow, dfz, dfx, pval1, pval2, pval4, pval3nc, rseed))
}

citbinm_linear <- function(L, G, T, maxit, nrow, dfz, dfx, pval1, pval2, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbinm_linear', PACKAGE = 'CITpkg', L, G, T, maxit, nrow, dfz, dfx, pval1, pval2, pval4, pval3nc, rseed))
}

citbinmcvr <- function(L, G, T, C, maxit, nrow, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbinmcvr', PACKAGE = 'CITpkg', L, G, T, C, maxit, nrow, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, rseed))
}

citbinmcvr_linear <- function(L, G, T, C, maxit, nrow, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, rseed) {
    invisible(.Call('_CITpkg_citbinmcvr_linear', PACKAGE = 'CITpkg', L, G, T, C, maxit, nrow, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, rseed))
}

citbinmp <- function(L, G, T, maxit, permit, permnum, nobs, dfz, dfx, pval1, pval2, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinmp', PACKAGE = 'CITpkg', L, G, T, maxit, permit, permnum, nobs, dfz, dfx, pval1, pval2, pval4, pval3nc, perm_index, rseed))
}

citbinmp_linear <- function(L, G, T, maxit, permit, permnum, nobs, dfz, dfx, pval1, pval2, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinmp_linear', PACKAGE = 'CITpkg', L, G, T, maxit, permit, permnum, nobs, dfz, dfx, pval1, pval2, pval4, pval3nc, perm_index, rseed))
}

citbinmpcvr <- function(L, G, T, C, maxit, permit, permnum, nobs, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinmpcvr', PACKAGE = 'CITpkg', L, G, T, C, maxit, permit, permnum, nobs, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, perm_index, rseed))
}

citbinmpcvr_linear <- function(L, G, T, C, maxit, permit, permnum, nobs, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinmpcvr_linear', PACKAGE = 'CITpkg', L, G, T, C, maxit, permit, permnum, nobs, dfz, dfx, dfc, pval1, pval2, pval4, pval3nc, perm_index, rseed))
}

citbinp <- function(L, G, T, maxit, permit, permnum, nrow, ncol, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinp', PACKAGE = 'CITpkg', L, G, T, maxit, permit, permnum, nrow, ncol, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed))
}

citbinp_linear <- function(L, G, T, maxit, permit, permnum, nrow, ncol, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinp_linear', PACKAGE = 'CITpkg', L, G, T, maxit, permit, permnum, nrow, ncol, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed))
}

citbinpcvr <- function(L, G, T, C, maxit, permit, boots, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinpcvr', PACKAGE = 'CITpkg', L, G, T, C, maxit, permit, boots, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed))
}

citbinpcvr_linear <- function(L, G, T, C, maxit, permit, boots, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed) {
    invisible(.Call('_CITpkg_citbinpcvr_linear', PACKAGE = 'CITpkg', L, G, T, C, maxit, permit, boots, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, pval3nc, perm_index, rseed))
}

citconlog2 <- function(L, G, T, nrow, ncol, pval, pval1, pval2, pval3, pval4, maxit, rseed) {
    invisible(.Call('_CITpkg_citconlog2', PACKAGE = 'CITpkg', L, G, T, nrow, ncol, pval, pval1, pval2, pval3, pval4, maxit, rseed))
}

citconlog2_linear <- function(L, G, T, nrow, ncol, pval, pval1, pval2, pval3, pval4, maxit, rseed) {
    invisible(.Call('_CITpkg_citconlog2_linear', PACKAGE = 'CITpkg', L, G, T, nrow, ncol, pval, pval1, pval2, pval3, pval4, maxit, rseed))
}

citconlog2cvr <- function(L, G, T, C, nrow, ncol, ncolc, pval, pval1, pval2, pval3, pval4, maxit, rseed) {
    invisible(.Call('_CITpkg_citconlog2cvr', PACKAGE = 'CITpkg', L, G, T, C, nrow, ncol, ncolc, pval, pval1, pval2, pval3, pval4, maxit, rseed))
}

citconlog2cvr_linear <- function(L, G, T, C, nrow, ncol, ncolc, pval, pval1, pval2, pval3, pval4, maxit, rseed) {
    invisible(.Call('_CITpkg_citconlog2cvr_linear', PACKAGE = 'CITpkg', L, G, T, C, nrow, ncol, ncolc, pval, pval1, pval2, pval3, pval4, maxit, rseed))
}

citconlog3p <- function(L, G, T, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed) {
    invisible(.Call('_CITpkg_citconlog3p', PACKAGE = 'CITpkg', L, G, T, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed))
}

citconlog3p_linear <- function(L, G, T, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed) {
    invisible(.Call('_CITpkg_citconlog3p_linear', PACKAGE = 'CITpkg', L, G, T, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed))
}

citconlog3pcvr <- function(L, G, T, C, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed) {
    invisible(.Call('_CITpkg_citconlog3pcvr', PACKAGE = 'CITpkg', L, G, T, C, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed))
}

citconlog3pcvr_linear <- function(L, G, T, C, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed) {
    invisible(.Call('_CITpkg_citconlog3pcvr_linear', PACKAGE = 'CITpkg', L, G, T, C, nrow, ncol, ncolc, pval1, pval2, pval3, pval4, maxit, permit, boots, Pind, rseed))
}

